/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Parser-1 */
#ifndef VERSION_Parser
#define VERSION_Parser "1"
#endif /* VERSION_Parser */
#ifndef MIN_VERSION_Parser
#define MIN_VERSION_Parser(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_Parser */
/* package Cabal-3.8.1.0 */
#ifndef VERSION_Cabal
#define VERSION_Cabal "3.8.1.0"
#endif /* VERSION_Cabal */
#ifndef MIN_VERSION_Cabal
#define MIN_VERSION_Cabal(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  8 || \
  (major1) == 3 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_VERSION_Cabal */
/* package Cabal-syntax-3.8.1.0 */
#ifndef VERSION_Cabal_syntax
#define VERSION_Cabal_syntax "3.8.1.0"
#endif /* VERSION_Cabal_syntax */
#ifndef MIN_VERSION_Cabal_syntax
#define MIN_VERSION_Cabal_syntax(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  8 || \
  (major1) == 3 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_VERSION_Cabal_syntax */
/* package base-4.17.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.17.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_base */
/* package haskeline-0.8.2 */
#ifndef VERSION_haskeline
#define VERSION_haskeline "0.8.2"
#endif /* VERSION_haskeline */
#ifndef MIN_VERSION_haskeline
#define MIN_VERSION_haskeline(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_haskeline */
/* package megaparsec-9.3.1 */
#ifndef VERSION_megaparsec
#define VERSION_megaparsec "9.3.1"
#endif /* VERSION_megaparsec */
#ifndef MIN_VERSION_megaparsec
#define MIN_VERSION_megaparsec(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  3 || \
  (major1) == 9 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_megaparsec */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package parser-combinators-1.3.0 */
#ifndef VERSION_parser_combinators
#define VERSION_parser_combinators "1.3.0"
#endif /* VERSION_parser_combinators */
#ifndef MIN_VERSION_parser_combinators
#define MIN_VERSION_parser_combinators(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_parser_combinators */
/* package split-0.2.3.5 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.5"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */
/* package template-haskell-2.19.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.19.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  19 || \
  (major1) == 2 && (major2) == 19 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package text-2.0.2 */
#ifndef VERSION_text
#define VERSION_text "2.0.2"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_text */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package unordered-containers-0.2.19.1 */
#ifndef VERSION_unordered_containers
#define VERSION_unordered_containers "0.2.19.1"
#endif /* VERSION_unordered_containers */
#ifndef MIN_VERSION_unordered_containers
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 19)
#endif /* MIN_VERSION_unordered_containers */

/* tool gcc-14.0.3 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.3"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.4.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.4.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.4.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.4.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.27.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.27.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  27 || \
  (major1) == 2 && (major2) == 27 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.4.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.4.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "Parser-1-Fl0Ezy7VbW0B8luKbuX2bd"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "Parser-1-Fl0Ezy7VbW0B8luKbuX2bd"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Parser-1 */
#ifndef VERSION_Parser
#define VERSION_Parser "1"
#endif /* VERSION_Parser */
#ifndef MIN_VERSION_Parser
#define MIN_VERSION_Parser(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_Parser */
/* package Cabal-3.8.1.0 */
#ifndef VERSION_Cabal
#define VERSION_Cabal "3.8.1.0"
#endif /* VERSION_Cabal */
#ifndef MIN_VERSION_Cabal
#define MIN_VERSION_Cabal(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  8 || \
  (major1) == 3 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_VERSION_Cabal */
/* package Cabal-syntax-3.8.1.0 */
#ifndef VERSION_Cabal_syntax
#define VERSION_Cabal_syntax "3.8.1.0"
#endif /* VERSION_Cabal_syntax */
#ifndef MIN_VERSION_Cabal_syntax
#define MIN_VERSION_Cabal_syntax(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  8 || \
  (major1) == 3 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_VERSION_Cabal_syntax */
/* package Parser-1 */
#ifndef VERSION_Parser
#define VERSION_Parser "1"
#endif /* VERSION_Parser */
#ifndef MIN_VERSION_Parser
#define MIN_VERSION_Parser(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_Parser */
/* package base-4.17.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.17.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_base */
/* package haskeline-0.8.2 */
#ifndef VERSION_haskeline
#define VERSION_haskeline "0.8.2"
#endif /* VERSION_haskeline */
#ifndef MIN_VERSION_haskeline
#define MIN_VERSION_haskeline(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_haskeline */
/* package megaparsec-9.3.1 */
#ifndef VERSION_megaparsec
#define VERSION_megaparsec "9.3.1"
#endif /* VERSION_megaparsec */
#ifndef MIN_VERSION_megaparsec
#define MIN_VERSION_megaparsec(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  3 || \
  (major1) == 9 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_megaparsec */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package parser-combinators-1.3.0 */
#ifndef VERSION_parser_combinators
#define VERSION_parser_combinators "1.3.0"
#endif /* VERSION_parser_combinators */
#ifndef MIN_VERSION_parser_combinators
#define MIN_VERSION_parser_combinators(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_parser_combinators */
/* package split-0.2.3.5 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.5"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */
/* package template-haskell-2.19.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.19.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  19 || \
  (major1) == 2 && (major2) == 19 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package text-2.0.2 */
#ifndef VERSION_text
#define VERSION_text "2.0.2"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_text */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package unordered-containers-0.2.19.1 */
#ifndef VERSION_unordered_containers
#define VERSION_unordered_containers "0.2.19.1"
#endif /* VERSION_unordered_containers */
#ifndef MIN_VERSION_unordered_containers
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 19)
#endif /* MIN_VERSION_unordered_containers */

/* tool gcc-14.0.3 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.3"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.4.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.4.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.4.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.4.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.27.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.27.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  27 || \
  (major1) == 2 && (major2) == 27 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.4.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.4.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "Parser-1-uJh4aA6mBA42kPGADcPpu-Parser"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
